name: covid1.1
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.1.19=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py37h06a4308_0
  - fastqc=0.11.9=0
  - font-ttf-dejavu-sans-mono=2.37=h6964260_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - glib=2.67.3=h36276a3_1
  - graphite2=1.3.14=h23475e2_0
  - harfbuzz=2.4.0=hca77d97_1
  - htslib=1.11=hd3b49d5_2
  - icu=58.2=he6710b0_3
  - jpeg=9b=h024ee3a_2
  - k8=0.2.5=he513fc3_0
  - krb5=1.18.2=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.1=h20c2e04_1
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - minimap2=2.17=hed695b0_3
  - ncurses=6.2=he6710b0_1
  - openjdk=8.0.152=h7b6447c_3
  - openssl=1.1.1i=h27cfd23_0
  - pango=1.45.3=hd140c19_0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - picard=2.25.0=0
  - pip=20.3.3=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - python=3.7.9=h7579374_0
  - qualimap=2.2.2a=1
  - r-base=3.2.2=0
  - readline=8.1=h27cfd23_0
  - samtools=1.11=h6270b1f_0
  - setuptools=52.0.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - chardet==4.0.0
    - click==7.1.2
    - coloredlogs==15.0
    - colormath==3.0.0
    - cycler==0.10.0
    - cython==0.29.21
    - decorator==4.4.2
    - future==0.18.2
    - humanfriendly==9.1
    - idna==2.10
    - importlib-metadata==3.4.0
    - jinja2==2.11.3
    - kiwisolver==1.3.1
    - lzstring==1.0.4
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - multiqc==1.9
    - networkx==2.5
    - numpy==1.20.1
    - nwalign3==0.1.2
    - pandas==1.2.2
    - pillow==8.1.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - simplejson==3.17.2
    - six==1.15.0
    - spectra==0.0.11
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3
    - zipp==3.4.0
prefix: /shared/workspace/software/anaconda3/envs/covid1.1
